##############################################################################
# Gemfile (and Gemfile.lock)
#
#  This file contains the Ruby gem manifest for Middlemac's dependencies.
#
#  To ensure that the correct gems are installed, do `bundle install`.
##############################################################################

source 'https://rubygems.org'


#######################################
# Middlemac, natch.
#######################################
gem 'middlemac', '~> 3.0.0.wip'
gem 'middleman-targets', '~> 1.0.7'
gem 'middleman-pagegroups', '~> 1.0.7'


#######################################
# Core gems
#######################################
gem 'middleman', '~> 4.1.7'
gem 'middleman-core'
gem 'middleman-cli'
gem 'middleman-livereload' # Live-reloading plugin
gem 'middleman-syntax'     # Syntax Highlighting
gem 'middleman-compass'


#######################################
# Core gems
#######################################
gem 'tzinfo-data', platforms: [:mswin, :mingw] # Time zone data for Windows
